### ISSUE TITLE
Imagens do site

### ISSUE THREAD

**Issue by Guimrl** [GranToro/grantoro.github.io#5]
![background 1280x720](https://user-images.githubusercontent.com/88007295/210459342-390e4082-2cdd-41d6-b5ba-576a63afd588.png)
![background 1920x1080](https://user-images.githubusercontent.com/88007295/210459345-6dcdd233-547c-47b7-8c74-26051e4b1096.png)

**Comment by GranToro** [comment]
![Logo](https://user-images.githubusercontent.com/121456169/210460727-b9c1c437-f0b6-409d-b06d-5ea51bb1f57e.png)
